### ISSUE TITLE
Checking my updates

### ISSUE THREAD

**Issue by bpffjl** [GSA/2233-USWDS-Digital-Dashboard#4]
@jwbowers I made changes based on our conversation to the power-calculations.rmd file. Would you have a look? The number of simulations is low just to help with writing the code. After your review, I'm going to execute the file over 5000 simulations. 

Thanks!

**Comment by jwbowers** [comment]
Looking at this now.

**Comment by jwbowers** [comment]
Closing with [cae98da](https://github.com/GSA/2233-USWDS-Digital-Dashboard/commit/cae98da17e2dc87fc8c424829d86ccebc18239b9)
